[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = []

[phases.build]
cmds = [
  "npm ci --prefix frontend --include=dev",
  "npm run build --prefix frontend",
  "npm ci --prefix backend --omit=dev"
]

[start]
cmd = "npm start"
