BEGIN;

ALTER TABLE ky_tuc_xa
  ADD COLUMN IF NOT EXISTS media_urls JSONB NOT NULL DEFAULT '[]'::JSONB;

ALTER TABLE phong_tro
  ADD COLUMN IF NOT EXISTS media_urls JSONB NOT NULL DEFAULT '[]'::JSONB;

COMMIT;
